import java.sql.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import javax.swing.JOptionPane;
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Issue_Books.java
 *
 * Created on Nov 21, 2018, 1:28:00 PM
 */

/**
 *
 * @author asus
 */

public class Issue_Books extends javax.swing.JFrame {
    int tid=0;
    public static Connection GetCon()
{
    Connection con;
    try {
        con=DriverManager.getConnection("jdbc:mysql://localhost:3306/library","root","maaz");
        return con;
        }
    catch (Exception e) {
        e.printStackTrace();
        return null;
        }
}
    public void execute(String query)
{
    Connection con = GetCon();
    Statement st;
    try {
        st = con.createStatement();
        if((st.executeUpdate(query))== 1){}
        else{
           JOptionPane.showMessageDialog(null,"Data not updated.");
            }
        }
   catch (Exception e) {
   e.printStackTrace();
                       }
}

    /** Creates new form Issue_Books */
    public Issue_Books() {
        initComponents();
        getMax_transid();
        DisableCtrl();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtMid = new javax.swing.JTextField();
        txtBid = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtIdate = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblTransid = new javax.swing.JLabel();
        btnIssue = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton2.setText("SAVE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setText("Book_ID");

        jLabel2.setText("Member_ID");

        txtMid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMidActionPerformed(evt);
            }
        });

        txtBid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBidActionPerformed(evt);
            }
        });
        txtBid.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtBidFocusLost(evt);
            }
        });

        jLabel4.setText("Issue Date");

        jLabel5.setText("[dd/mm/yyyy]");

        jLabel3.setText("TRANSACTION ID :");

        lblTransid.setText("jLabel6");

        btnIssue.setText("Issue");
        btnIssue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIssueActionPerformed(evt);
            }
        });

        btnClear.setText("Clear");

        btnClose.setText("Close");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(btnIssue)
                .addGap(28, 28, 28)
                .addComponent(jButton2)
                .addGap(27, 27, 27)
                .addComponent(btnClear)
                .addGap(26, 26, 26)
                .addComponent(btnClose)
                .addContainerGap(527, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(33, 33, 33)))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtIdate, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(137, 137, 137))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(lblTransid, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtBid, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtMid, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 297, Short.MAX_VALUE)))
                .addGap(309, 309, 309))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblTransid))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(txtBid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtMid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIssue)
                    .addComponent(jButton2)
                    .addComponent(btnClear)
                    .addComponent(btnClose))
                .addGap(37, 37, 37))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
public void getBookID()
{
    try
    {
            Class.forName("java.sql.Driver");
            String strCon="jdbc:mysql://localhost/library";
            Connection con= DriverManager.getConnection(strCon,"root","maaz");
            Statement stm=con.createStatement();

            String str ="SELECT * FROM add_books where book_id="+txtBid.getText();
            ResultSet rs= stm.executeQuery(str);
            if(!rs.next())
            {
                JOptionPane.showMessageDialog(null,"Book Id Not Found ! Enter Correct Book ID");
                txtBid.setText("");
                
                txtBid.setFocusable(true);
              int bid=rs.getInt("Book_ID") ;
              String b=rs.getString("Book_name");
              String c=rs.getString("Category");
              String q=rs.getString("Quantity");
              //JOptionPane.showMessageDialog(null,"Values ="+bid+" "+c+" "+q);
            }
            
            

             rs.close();
             stm.close();
             con.close();
    }
    catch(SQLException e){
            JOptionPane.showMessageDialog(null, e.getMessage());
    }
    catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
}
public void getMax_transid()
{
    
    try
    {
            
            Class.forName("java.sql.Driver");
            String strCon="jdbc:mysql://localhost/library";
            Connection con= DriverManager.getConnection(strCon,"root","maaz");
            Statement stm=con.createStatement();

            String str ="SELECT max(transid) FROM issue_books";
            ResultSet rs= stm.executeQuery(str);
            if(!rs.next())
            {
                tid=1;
            }
            else
            {
                 tid=rs.getInt("max(transid)")+1 ;
                 lblTransid.setText(""+tid);
            }
             rs.close();
             stm.close();
             con.close();
    }
    catch(SQLException e){
            JOptionPane.showMessageDialog(null, e.getMessage());
    }
    catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }

}
public void DisableCtrl()
{
    txtBid.setEditable(false);
    txtIdate.setEditable(false);
    txtMid.setEditable(false);

    jButton2.setEnabled(false);
    btnClear.setEnabled(false);
    btnClose.setEnabled(false);
    
    
}
public void EnableCtrl()
{
    txtBid.setEditable(true);
    txtIdate.setEditable(true);
    txtMid.setEditable(true);

    jButton2.setEnabled(true);
    btnClear.setEnabled(true);
    btnClose.setEnabled(true);


}
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int mid= Integer.parseInt(txtMid.getText());
        int bid= Integer.parseInt(txtBid.getText());
        String dt=txtIdate.getText();
       // String n3= m3.getText();
        try {
           Class.forName("java.sql.Driver");
            String strCon="jdbc:mysql://localhost/library";
            Connection con= DriverManager.getConnection(strCon,"root","maaz");
            Statement stm=con.createStatement();

            String query = "insert into issue_books values("+bid+","+mid+",'"+dt+"',"+tid+")";
            stm.executeUpdate(query);
           // String query2="update add_books set IRqty=Irqty+1 where Books_ID="+bid+"";
           // stm.executeUpdate(query2);;

            JOptionPane.showMessageDialog(null,"Data updated Successfully");
            
            txtMid.setText("");
            txtBid.setText("");
            txtIdate.setText("");
            DisableCtrl();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,e);
       }        // TODO add your handling code here:
  
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtMidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMidActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_txtMidActionPerformed

    private void txtBidFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBidFocusLost
        // TODO add your handling code here:
        //JOptionPane.showMessageDialog(null,"Hello");
        getBookID();
}//GEN-LAST:event_txtBidFocusLost

    private void txtBidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBidActionPerformed

    private void btnIssueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIssueActionPerformed
        // TODO add your handling code here:
        EnableCtrl();
        getMax_transid();
    }//GEN-LAST:event_btnIssueActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Issue_Books().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnIssue;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblTransid;
    private javax.swing.JTextField txtBid;
    private javax.swing.JTextField txtIdate;
    private javax.swing.JTextField txtMid;
    // End of variables declaration//GEN-END:variables

}
