import java.sql.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import javax.swing.JOptionPane;

public class QuizPlay extends javax.swing.JFrame
{
    Connection con=null;
    Statement stm=null;
    ResultSet rs= null;
    String strCon="jdbc:mysql://localhost/library";
    String cans="";
    int Score=0;
    /** Creates new form QuizPlay */
    public QuizPlay() {
        initComponents();
      //  btnNext.setEnabled(false);
        try
        {
            Class.forName("java.sql.Driver");
            //String strCon="jdbc:mysql://localhost/library";
            con= DriverManager.getConnection(strCon,"root","maaz");
            stm=con.createStatement();

            String str ="SELECT * FROM qbank1";
            rs= stm.executeQuery(str);
            rs.next();

            lblQuest.setText(""+rs.getString("quest"));
            lblOp1.setText(""+rs.getString("A"));
            lblOp2.setText(""+rs.getString("B"));
            lblOp3.setText(""+rs.getString("C"));
            lblcorrect.setText(""+rs.getString("cor_opt"));
            cans=rs.getString("cor_opt");
            cmbCorrOpt.setSelectedIndex(0);
            //calcScore();
         //   lblScore.setText(" "+Score);
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }


 }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        lblQuest = new javax.swing.JLabel();
        btnNext = new javax.swing.JButton();
        lblOp2 = new javax.swing.JLabel();
        lblOp1 = new javax.swing.JLabel();
        lblOp3 = new javax.swing.JLabel();
        cmbCorrOpt = new javax.swing.JComboBox();
        lblOp4 = new javax.swing.JLabel();
        lblOp5 = new javax.swing.JLabel();
        lblOp6 = new javax.swing.JLabel();
        lblFooter = new javax.swing.JLabel();
        lblcorrect = new javax.swing.JLabel();
        lblScore = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblQuest.setBackground(new java.awt.Color(102, 102, 255));
        lblQuest.setFont(new java.awt.Font("Verdana", 0, 14));
        lblQuest.setForeground(new java.awt.Color(204, 255, 204));
        lblQuest.setText("Question");
        lblQuest.setOpaque(true);

        btnNext.setBackground(new java.awt.Color(51, 51, 255));
        btnNext.setForeground(new java.awt.Color(255, 0, 204));
        btnNext.setText("NEXT >>");
        btnNext.setOpaque(false);
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        lblOp2.setText("jLabel1");

        lblOp1.setText("jLabel1");

        lblOp3.setText("jLabel1");

        cmbCorrOpt.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Choose ...", "A", "B", "C" }));
        cmbCorrOpt.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbCorrOptItemStateChanged(evt);
            }
        });

        lblOp4.setText("A");

        lblOp5.setText("B");

        lblOp6.setText("C");

        lblFooter.setBackground(new java.awt.Color(102, 102, 255));
        lblFooter.setFont(new java.awt.Font("Verdana", 0, 14));
        lblFooter.setForeground(new java.awt.Color(204, 255, 204));
        lblFooter.setOpaque(true);

        lblScore.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbCorrOpt, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblQuest, javax.swing.GroupLayout.PREFERRED_SIZE, 528, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblOp6)
                                    .addComponent(lblOp5)
                                    .addComponent(lblOp4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblOp3)
                                    .addComponent(lblOp2)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblOp1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblcorrect))))
                            .addComponent(lblFooter, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnNext)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addContainerGap(193, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(470, Short.MAX_VALUE)
                .addComponent(lblScore)
                .addGap(263, 263, 263))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addComponent(lblQuest, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblOp1)
                                .addGap(18, 18, 18)
                                .addComponent(lblOp2)
                                .addGap(18, 18, 18)
                                .addComponent(lblOp3))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblOp4)
                                .addGap(18, 18, 18)
                                .addComponent(lblOp5)
                                .addGap(18, 18, 18)
                                .addComponent(lblOp6)))
                        .addGap(18, 18, 18)
                        .addComponent(cmbCorrOpt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(lblcorrect)
                        .addGap(57, 57, 57)
                        .addComponent(lblScore)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnNext, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblFooter, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE))
                .addGap(190, 190, 190))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
public void chkAns()
{
    String uans=(String) cmbCorrOpt.getSelectedItem();
    //JOptionPane.showMessageDialog(null, uans);
    if(cans.equalsIgnoreCase(uans)==true)
    {
        
        Score+=10;
    }
    else
    {
        
        Score-=5;
    }

}


public boolean isCorrectAnsSelected()
{
    if(cmbCorrOpt.getSelectedIndex()==0)
            return false;
    else
            return true;
}
    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        

        try
        {
            boolean status=isCorrectAnsSelected();
            if(status==false)
            {
            //btnNext.setEnabled(true);
                JOptionPane.showMessageDialog(null, "Correct Answer not selected...","Input Required",1);
                return;
            }
            else
            {
                chkAns();
            }
            rs.next();

            if(rs.isAfterLast())
            {
                rs.close();
                stm.close();
                con.close();
                JOptionPane.showMessageDialog(null, "Thanks for Playing Quiz Your Score is : "+Score);
                System.exit(0);
            }

            lblQuest.setText(""+rs.getString("quest"));
            lblOp1.setText(""+rs.getString("A"));
            lblOp2.setText(""+rs.getString("B"));
            lblOp3.setText(""+rs.getString("C"));
            lblcorrect.setText(""+rs.getString("cor_opt"));
            cans=rs.getString("cor_opt");
            cmbCorrOpt.setSelectedIndex(0);
            

        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex.getMessage());
         }
    }//GEN-LAST:event_btnNextActionPerformed

    private void cmbCorrOptItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbCorrOptItemStateChanged
        // TODO add your handling code here:
        //chkAns();
        //lblScore.setText(" "+Score);
    }//GEN-LAST:event_cmbCorrOptItemStateChanged

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuizPlay().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNext;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox cmbCorrOpt;
    private javax.swing.JLabel lblFooter;
    private javax.swing.JLabel lblOp1;
    private javax.swing.JLabel lblOp2;
    private javax.swing.JLabel lblOp3;
    private javax.swing.JLabel lblOp4;
    private javax.swing.JLabel lblOp5;
    private javax.swing.JLabel lblOp6;
    private javax.swing.JLabel lblQuest;
    private javax.swing.JLabel lblScore;
    private javax.swing.JLabel lblcorrect;
    // End of variables declaration//GEN-END:variables

}
